apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.fullname }}
data:
  pghero.yml: |-
    databases:
      main:
        url: {{ .Values.databases.url }}

      # Add more databases
      other:
        url: <%= ENV["OTHER_DATABASE_URL"] %>

    # Minimum time for long running queries
    # long_running_query_sec: 60

    # Minimum average time for slow queries
    # slow_query_ms: 20

    # Minimum calls for slow queries
    # slow_query_calls: 100

    # Minimum connections for high connections warning
    # total_connections_threshold: 500

    # Statement timeout for explain
    # explain_timeout_sec: 10

    # Time zone
    # time_zone: "Pacific Time (US & Canada)"
