apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "helmchart-pghero.fullname" . }}
  labels:
    app: pghero
spec:
  selector:
    matchLabels: 
      app: pghero
  replicas: {{ .Values.replicas }}
  template:
    metadata:
      labels:
        app: pghero
    spec:
      containers:
      - name: pghero
        image: ankane/pghero:v2.8.1
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        volumeMounts:
        - name: pghero-config
          mountPath: /app/config/pghero.yml
          readOnly: true
          subPath: pghero.yml
      volumes:
      - name: pghero-config
        secret:
          secretName: {{ include "helmchart-pghero.fullname" . }}
