{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    {{- toYaml .Values.ingress.annotations | nindent 4 }}  
  name: {{ include "helmchart-pghero.fullname" . }}
  labels:
    ingressClassName: openshift-default
spec:
  ingressClassName: openshift-default
  {{- if .Values.ingress.tls.enabled }}
  tls:
  - hosts: 
    - {{ .Values.ingress.host }}
    secretName: {{ include "helmchart-pghero.fullname" . }}-tls
  {{ end }}  
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - backend:
          service:
            name: {{ include "helmchart-pghero.fullname" . }}
            port: 
              number: {{ .Values.service.port }}
              
        path: /
        pathType: Prefix
{{ end }}                           
